### ISSUE TITLE
Unclear what is going on

### ISSUE THREAD

**Issue by levino** [okfde/froide-food#10]
Please see this entry: https://fragdenstaat.de/anfrage/kontrollbericht-zu-fleischerei-neuling/

I do not get what is going on: So the request is marked "completed" in the map (green dot for the shop) but there are not reports to download. Also it is totally unclear how the request was completed. I can only see in very small font that "Martin Henke set status to "no information available".

![Selection_017](https://user-images.githubusercontent.com/1150767/62140365-29366480-b2eb-11e9-8d2a-97085d17840d.jpg)

So my guess is this: This shop has never been checked for hygiene. Ever. So the Veterinäramt did not send any reports.

If that is the case, it should be made more prominent. It should say something along the lines:

"Das Veterinäramt hat geantwortet, dass bislang keine Kontrollen bzw. keine Kontrollen mit Beanstandungen statt gefunden haben."

Also I would expect a new `<div class="message-container">` wrapping this information to make it more prominent. Right now it just looks like the request has timed out.

**Also** I would expect a button that allows me to start a new request (maybe the earliest 3 months after the first request as a spam protection or so).

**Comment by stefanw** [comment]
A hint was added to the page stating the current reply policy of the public authority in question.

Users give the state of their own requests and sometimes mislabel them. It's not a software issue.
