### ISSUE TITLE
Map missing some pending requests

### ISSUE THREAD

**Issue by Matthias84** [okfde/froide-food#9]
Hi, I noticed, that the map is missing some POIs which have already requests
* https://fragdenstaat.de/a/53472
* https://fragdenstaat.de/a/53471

But the map doesn't highlight them in yellow (pending). Maybe this is an more generic problem?

**Comment by stefanw** [comment]
Sometimes users make requests outside of the Topf Secret map application. This leads to missing meta data about the location and a pin cannot be shown. We have improved this through hints provided to the users where to make Topf Secret requests.
